FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y cgi-mapserver mapserver-bin tinyows && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["/usr/lib/cgi-bin/mapserv", "-v"]
